### ISSUE TITLE
seems java issue when doing opengrok indexing

### ISSUE THREAD

**Issue by xiangp126** [xiangp126/cc-opengrok#2]
08:15:05 WARNING: Failed to determineCurrentVersion for /opt/o-source: java.io.IOException: error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
fatal: bad object HEAD

08:15:05 WARNING: Non-zero exit status 128 from command [/usr/local/bin/git, log, --abbrev-commit, --abbrev=8, --name-only, --pretty=fuller, --date=iso8601-strict, --, /opt/o-source] in directory /opt/o-source: error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
error: packfile .git/objects/pack/pack-d66eed4a94133ad4ab2fae55a3f561520b58ce62.pack does not match index
fatal: bad object HEAD

08:15:05 WARNING: An error occurred while creating cache for /opt/o-source/ (GitRepository)
org.opensolaris.opengrok.history.HistoryException: Failed to get history for: "/opt/o-source" Exit code: 128
        at org.opensolaris.opengrok.history.GitHistoryParser.parse(GitHistoryParser.java:181)
        at org.opensolaris.opengrok.history.GitRepository.getHistory(GitRepository.java:484)
        at org.opensolaris.opengrok.history.Repository.createCache(Repository.java:332)
        at org.opensolaris.opengrok.history.HistoryGuru.createCache(HistoryGuru.java:587)
        at org.opensolaris.opengrok.history.HistoryGuru.access$000(HistoryGuru.java:63)
        at org.opensolaris.opengrok.history.HistoryGuru$1.run(HistoryGuru.java:638)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by xiangp126** [comment]
works well on Mac with Java compiled using HomeBrew

**Comment by xiangp126** [comment]
This may be a joke, it was my mistake

I put some source under /source
but I typed `git init` for that directory by accident, and forgot it after that, ha..

```bash
and '08:15:05 WARNING: Failed to determineCurrentVersion for /opt/o-source: java.io.IOExce'
points to that directory
```
